config/routes.rb
Rails.application.routes.draw do

  resources :requests
  root "requests#index"

  post "/requests/status/:id" => "requests#status", as: :status_update
  get "/requests/search" => "requests#search", as: :search
  
end

app/models/request.rb
class Request < ActiveRecord::Base
  # Add validation to ensure that there is a name and email

  validates :name, presence: true
  validates :email, presence: true

  # Sort
  def self.sort_by_status
    order("status DESC")
  end

  # Search method here!
  def self.wildcard_search(str)
  where(["name ILIKE ? OR email ILIKE ? OR message ILIKE ? OR department ILIKE?", "%#{str}%", "%#{str}%","%#{str}%", "%#{str}%"])
  end

  def self.search(str)
    if str
      find(:all, :conditions => ["name ILIKE ? OR email ILIKE ? OR message ILIKE ? OR department ILIKE?", "%#{str}%", "%#{str}%","%#{str}%", "%#{str}%"])
    else
      find(:all)
    end
  end

  # def self.fill_status
  #   where("status = nil").each do |element|
  #     element.update(status: "Un-done")
  #   end
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController

  before_action :find_request, only: [:show, :edit, :update, :destroy, :status]
  # show all the requests available
  def index
    @request = Request.all.sort_by_status
  end

  def new
    @request = Request.new
  end

  def create
    @request = Request.new(req_params)
    if @request.save
      redirect_to request_path(@request), notice: "Thanks for submitting a request!"
    else
      flash[:alert] = "Request failed. Please try again"
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @request.update req_params
      redirect_to requests_path(@request), notice: "Request successfully updated"
    else
      flash[:alert] = "Request update failed. Try again."
      render :edit
    end
  end

  def destroy
    @request.destroy
    redirect_to requests_path, notice: "Request successfully deleted."
  end

  def status
    if @request.status == "Un-done"
      @request.update status: "Done"
      redirect_to requests_path, notice: "Request marked done"
    else
      @request.update status: "Un-done"
      redirect_to requests_path, notice: "Request marked un-done"
    end
  end

  def search
    @request = Request.search(:search.to_s)
  end

  private

  def req_params
    req_params = params.require(:request).permit(:name,:email,:department,:message)
  end

  def find_request
    @request = Request.search(:search.to_s)
    @request = Request.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TechSupport</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar">
    <%= link_to "Home", requests_path %> |
    <%= link_to "Submit New Request", new_request_path %>
  </div>
  <div class="image-container">
    <%= image_tag("service.png")%>
  </div>
  <hr>
<%= yield %>

</body>
</html>

app/views/requests/edit.html.erb
<h1>Edit Request</h1>
<%= @request.errors.full_messages.join(", ") %>
<%= form_for @request do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div>
    <span>Department: </span>
    <%= f.label :department_sales, "Sales" %>
    <%= f.radio_button :department, "Sales"%>
    <%= f.label :department_marketing, "Marketing" %>
    <%= f.radio_button :department, "Marketing" %>
    <%= f.label :department_technical, "Technical" %>
    <%= f.radio_button :department, "Technical" %>
  </div>
  <div>
    <%= f.label :message %>
    <%= f.text_area :message %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/requests/index.html.erb
<h1>All Tech Support Requests</h1>
<span class="status-change"><%= notice || alert%></span>

<%= form_tag("/requests/search", method: "get") do %>
  <%= label_tag ("Search for:") %>
  <%= text_field_tag :search%>
  <%= submit_tag("Search") %>
<% end %>


<table>
  <tr>
    <th>Request ID</th>
    <th>Name</th>
    <th>Email</th>
    <th>Department</th>
    <th>Message</th>
    <th>Status</th>
  </tr>
  <% @request.each do |request| %>
    <tr>
      <td><%= link_to request.id, request_path(request) %></td>
      <td><%= request.name %></td>
      <td><%= request.email %></td>
      <td><%= request.department %></td>
      <td><%= request.message %></td>
      <td>
        <%= link_to "Update", edit_request_path(request) %> |
        <%= link_to "Delete",
                     request_path(request),
                     method: :delete,
                     data: {confirm: "Are you sure you want to delete the request?"} %>
        <%= button_to request.status, status_update_path(request)  %>
      </td>
    </tr>
  <% end %>
</table>

app/views/requests/new.html.erb
<h1>Submit a New request</h1>
<%= @request.errors.full_messages.join(", ") %>
<%= form_for @request do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div>
    <span>Department: </span>
    <%= f.label :department_sales, "Sales" %>
    <%= f.radio_button :department, "Sales"%>
    <%= f.label :department_marketing, "Marketing" %>
    <%= f.radio_button :department, "Marketing" %>
    <%= f.label :department_technical, "Technical" %>
    <%= f.radio_button :department, "Technical" %>
  </div>
  <div>
    <%= f.label :message %>
    <%= f.text_area :message %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/requests/show.html.erb
<h3>Request ID: <%= @request.id %></h3>
<br>
<span>Contact Name: <%= @request.name %></span>
<br>
<span>Contact Email: <%= @request.email %></span>
<p>Message: <%= @request.message %></p>
<br>

<%= link_to "Update Request", edit_request_path(@request) %> |
<%= link_to "Delete Request",
             request_path(@request),
             method: :delete,
             data: {confirm: "Are you sure you want to delete the request?"} %>